version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: holbies_db
      POSTGRES_USER: holbies_user
      POSTGRES_PASSWORD: holbies_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://holbies_user:holbies_password@db/holbies_db
      SECRET_KEY: your-super-secret-key-here-change-in-production
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
